
// Generated by Cadence Genus(TM) Synthesis Solution 23.17-s085_1
// Generated on: May 17 2026 12:33:10 +07 (May 17 2026 05:33:10 UTC)

// Verification Directory fv/viterbi_decoder 

module viterbi_decoder(clk, rst_n, en, i_data, o_data, o_done);
  input clk, rst_n, en;
  input [15:0] i_data;
  output [7:0] o_data;
  output o_done;
  wire clk, rst_n, en;
  wire [15:0] i_data;
  wire [7:0] o_data;
  wire o_done;
  wire [1:0] pm00;
  wire [1:0] pm10;
  wire [1:0] pm11;
  wire [1:0] pm01;
  wire [3:0] dec_s5;
  wire [3:0] dec_s3;
  wire [3:0] dec_s2;
  wire [3:0] dec_s4;
  wire [1:0] dec_s6;
  wire [15:0] rx_reg;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, dec_s7, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_261, \u_memory_rx_reg[0]_297 , \u_memory_rx_reg[1]_298
       , \u_memory_rx_reg[2]_299 , \u_memory_rx_reg[3]_300 ,
       \u_memory_rx_reg[4]_301 , \u_memory_rx_reg[5]_302 ;
  wire \u_memory_rx_reg[6]_303 , \u_memory_rx_reg[7]_304 ,
       \u_memory_rx_reg[8]_305 , \u_memory_rx_reg[9]_306 ,
       \u_memory_rx_reg[10]_307 , \u_memory_rx_reg[11]_308 ;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  DFFRX1 \u_memory_pm00_reg[0] (.RN (rst_n), .CK (clk), .D (n_237), .Q
       (pm00[0]), .QN (n_28));
  DFFSX1 \u_memory_pm10_reg[1] (.SN (rst_n), .CK (clk), .D (n_240), .Q
       (pm10[1]), .QN (n_24));
  DFFRX1 \u_memory_pm00_reg[1] (.RN (rst_n), .CK (clk), .D (n_239), .Q
       (pm00[1]), .QN (n_19));
  DFFSX1 \u_memory_pm10_reg[0] (.SN (rst_n), .CK (clk), .D (n_232), .Q
       (pm10[0]), .QN (UNCONNECTED));
  DFFSX1 \u_memory_pm11_reg[1] (.SN (rst_n), .CK (clk), .D (n_235), .Q
       (pm11[1]), .QN (n_52));
  DFFSX1 \u_memory_pm01_reg[1] (.SN (rst_n), .CK (clk), .D (n_231), .Q
       (pm01[1]), .QN (n_32));
  DFFSX1 \u_memory_pm01_reg[0] (.SN (rst_n), .CK (clk), .D (n_230), .Q
       (pm01[0]), .QN (UNCONNECTED0));
  DFFSX1 \u_memory_pm11_reg[0] (.SN (rst_n), .CK (clk), .D (n_229), .Q
       (pm11[0]), .QN (n_0));
  OAI221X1 g6477__2398(.A0 (n_238), .A1 (n_222), .B0 (n_24), .B1
       (n_234), .C0 (n_233), .Y (n_240));
  OAI22X1 g6479__5107(.A0 (n_238), .A1 (n_228), .B0 (n_19), .B1
       (n_236), .Y (n_239));
  OAI22X1 g6474__6260(.A0 (n_238), .A1 (n_227), .B0 (n_28), .B1
       (n_236), .Y (n_237));
  OAI221X1 g6476__4319(.A0 (n_238), .A1 (n_213), .B0 (n_52), .B1
       (n_234), .C0 (n_233), .Y (n_235));
  OAI211X1 g6472__8428(.A0 (n_238), .A1 (n_223), .B0 (n_233), .C0
       (n_55), .Y (n_232));
  OAI221X1 g6478__5526(.A0 (n_238), .A1 (n_207), .B0 (n_32), .B1
       (n_234), .C0 (n_233), .Y (n_231));
  DFFRX1 \u_memory_dec_s5_reg[0] (.RN (rst_n), .CK (clk), .D (n_224),
       .Q (dec_s5[0]), .QN (UNCONNECTED1));
  DFFRX1 \u_memory_dec_s3_reg[0] (.RN (rst_n), .CK (clk), .D (n_218),
       .Q (dec_s3[0]), .QN (UNCONNECTED2));
  DFFRX1 \u_memory_dec_s5_reg[2] (.RN (rst_n), .CK (clk), .D (n_216),
       .Q (dec_s5[2]), .QN (UNCONNECTED3));
  OAI211X1 g6473__6783(.A0 (n_238), .A1 (n_203), .B0 (n_233), .C0
       (n_54), .Y (n_230));
  OAI211X1 g6475__3680(.A0 (n_238), .A1 (n_209), .B0 (n_233), .C0
       (n_56), .Y (n_229));
  DFFRX1 \u_memory_dec_s3_reg[2] (.RN (rst_n), .CK (clk), .D (n_219),
       .Q (dec_s3[2]), .QN (UNCONNECTED4));
  DFFRX1 u_memory_dec_s7_reg(.RN (rst_n), .CK (clk), .D (n_214), .Q
       (dec_s7), .QN (n_1));
  AOI22X1 g6490__1617(.A0 (n_196), .A1 (n_226), .B0 (n_201), .B1
       (n_225), .Y (n_228));
  AOI22X1 g6491__2802(.A0 (n_197), .A1 (n_226), .B0 (n_184), .B1
       (n_225), .Y (n_227));
  DFFRX1 \u_memory_dec_s5_reg[1] (.RN (rst_n), .CK (clk), .D (n_210),
       .Q (dec_s5[1]), .QN (UNCONNECTED5));
  DFFRX1 \u_memory_dec_s3_reg[1] (.RN (rst_n), .CK (clk), .D (n_204),
       .Q (dec_s3[1]), .QN (UNCONNECTED6));
  DFFRX1 \u_memory_dec_s5_reg[3] (.RN (rst_n), .CK (clk), .D (n_212),
       .Q (dec_s5[3]), .QN (UNCONNECTED7));
  DFFRX1 \u_memory_dec_s3_reg[3] (.RN (rst_n), .CK (clk), .D (n_205),
       .Q (dec_s3[3]), .QN (UNCONNECTED8));
  MX2X1 g6489__1705(.A (n_226), .B (dec_s5[0]), .S0 (n_215), .Y
       (n_224));
  AOI22X1 g6492__5122(.A0 (n_193), .A1 (n_221), .B0 (n_183), .B1
       (n_220), .Y (n_223));
  AOI22X1 g6493__8246(.A0 (n_192), .A1 (n_221), .B0 (n_200), .B1
       (n_220), .Y (n_222));
  MX2X1 g6501__7098(.A (dec_s3[2]), .B (n_221), .S0 (n_217), .Y
       (n_219));
  MX2X1 g6499__6131(.A (dec_s3[0]), .B (n_226), .S0 (n_217), .Y
       (n_218));
  MX2X1 g6496__1881(.A (n_221), .B (dec_s5[2]), .S0 (n_215), .Y
       (n_216));
  MX2X1 g6503__5115(.A (dec_s7), .B (n_226), .S0 (n_146), .Y (n_214));
  AOI22X1 g6497__7482(.A0 (n_186), .A1 (n_211), .B0 (n_195), .B1
       (n_208), .Y (n_213));
  MX2X1 g6495__4733(.A (n_211), .B (dec_s5[3]), .S0 (n_215), .Y
       (n_212));
  MX2X1 g6494__6161(.A (n_206), .B (dec_s5[1]), .S0 (n_215), .Y
       (n_210));
  AOI22X1 g6498__9315(.A0 (n_187), .A1 (n_211), .B0 (n_181), .B1
       (n_208), .Y (n_209));
  AOI22X1 g6504__9945(.A0 (n_189), .A1 (n_206), .B0 (n_199), .B1
       (n_202), .Y (n_207));
  MX2X1 g6502__2883(.A (dec_s3[3]), .B (n_211), .S0 (n_217), .Y
       (n_205));
  MX2X1 g6500__2346(.A (dec_s3[1]), .B (n_206), .S0 (n_217), .Y
       (n_204));
  AOI22X1 g6505__1666(.A0 (n_190), .A1 (n_206), .B0 (n_179), .B1
       (n_202), .Y (n_203));
  INVX2 g6507(.A (n_226), .Y (n_225));
  CLKINVX2 g6506(.A (n_220), .Y (n_221));
  CLKAND2X2 g6509__7410(.A (n_201), .B (n_198), .Y (n_226));
  INVX2 g6510(.A (n_202), .Y (n_206));
  NAND2X1 g6508__6417(.A (n_200), .B (n_194), .Y (n_220));
  INVX2 g6511(.A (n_208), .Y (n_211));
  NAND2X1 g6512__5477(.A (n_199), .B (n_191), .Y (n_202));
  OAI21X1 g6514__2398(.A0 (n_197), .A1 (n_185), .B0 (n_196), .Y
       (n_198));
  NAND2X1 g6513__5107(.A (n_195), .B (n_188), .Y (n_208));
  OAI21X1 g6515__6260(.A0 (n_193), .A1 (n_182), .B0 (n_192), .Y
       (n_194));
  OAI21X1 g6516__4319(.A0 (n_190), .A1 (n_178), .B0 (n_189), .Y
       (n_191));
  OAI21X1 g6517__8428(.A0 (n_187), .A1 (n_180), .B0 (n_186), .Y
       (n_188));
  CLKINVX1 g6527(.A (n_184), .Y (n_185));
  CLKINVX1 g6529(.A (n_182), .Y (n_183));
  CLKINVX1 g6526(.A (n_180), .Y (n_181));
  CLKINVX1 g6528(.A (n_178), .Y (n_179));
  OAI211X1 g6531__5526(.A0 (n_169), .A1 (n_148), .B0 (n_155), .C0
       (n_158), .Y (n_184));
  AOI211X1 g6535__6783(.A0 (n_177), .A1 (n_159), .B0 (n_157), .C0
       (n_156), .Y (n_182));
  NAND2X1 g6518__3680(.A (n_177), .B (n_161), .Y (n_192));
  NAND2X1 g6519__1617(.A (n_177), .B (n_176), .Y (n_201));
  NAND2X1 g6521__2802(.A (n_2), .B (n_176), .Y (n_200));
  AOI211X1 g6530__1705(.A0 (n_175), .A1 (n_172), .B0 (n_171), .C0
       (n_170), .Y (n_180));
  NAND2X1 g6525__5122(.A (n_173), .B (n_174), .Y (n_195));
  NAND2X1 g6523__8246(.A (n_175), .B (n_174), .Y (n_199));
  AOI211X1 g6533__7098(.A0 (n_173), .A1 (n_172), .B0 (n_171), .C0
       (n_170), .Y (n_178));
  OR2X1 g6520__6131(.A (n_169), .B (n_160), .Y (n_196));
  NAND2X1 g6524__1881(.A (n_173), .B (n_162), .Y (n_189));
  OAI211X1 g6532__5115(.A0 (n_169), .A1 (n_168), .B0 (n_167), .C0
       (n_166), .Y (n_193));
  OAI211X1 g6537__7482(.A0 (n_13), .A1 (n_165), .B0 (n_164), .C0
       (n_163), .Y (n_190));
  OAI211X1 g6536__4733(.A0 (n_4), .A1 (n_168), .B0 (n_167), .C0
       (n_166), .Y (n_197));
  OAI211X1 g6534__6161(.A0 (n_16), .A1 (n_165), .B0 (n_164), .C0
       (n_163), .Y (n_187));
  NAND2X1 g6538__9315(.A (n_175), .B (n_162), .Y (n_186));
  CLKINVX1 g6539(.A (n_160), .Y (n_161));
  AOI21X1 g6540__9945(.A0 (n_152), .A1 (n_153), .B0 (n_159), .Y
       (n_176));
  CLKINVX1 g6554(.A (n_157), .Y (n_158));
  CLKINVX1 g6555(.A (n_155), .Y (n_156));
  AOI21X1 g6544__2883(.A0 (n_154), .A1 (n_151), .B0 (n_172), .Y
       (n_174));
  DFFRX1 \u_memory_dec_s2_reg[0] (.RN (rst_n), .CK (clk), .D (n_138),
       .Q (dec_s2[0]), .QN (UNCONNECTED9));
  DFFRX1 \u_memory_dec_s2_reg[2] (.RN (rst_n), .CK (clk), .D (n_140),
       .Q (dec_s2[2]), .QN (UNCONNECTED10));
  DFFRX1 \u_memory_dec_s4_reg[2] (.RN (rst_n), .CK (clk), .D (n_139),
       .Q (dec_s4[2]), .QN (UNCONNECTED11));
  DFFRX1 \u_memory_dec_s4_reg[0] (.RN (rst_n), .CK (clk), .D (n_141),
       .Q (dec_s4[0]), .QN (UNCONNECTED12));
  DFFRX1 \u_memory_dec_s6_reg[0] (.RN (rst_n), .CK (clk), .D (n_147),
       .Q (dec_s6[0]), .QN (UNCONNECTED13));
  OAI21X1 g6541__2346(.A0 (n_154), .A1 (n_149), .B0 (n_168), .Y
       (n_160));
  AOI21X1 g6543__1666(.A0 (n_154), .A1 (n_150), .B0 (n_145), .Y
       (n_162));
  NOR2X1 g6558__7410(.A (n_154), .B (n_153), .Y (n_157));
  NAND2X1 g6559__6417(.A (n_154), .B (n_153), .Y (n_155));
  NOR2X1 g6562__5477(.A (n_152), .B (n_151), .Y (n_171));
  AND2X1 g6563__2398(.A (n_151), .B (n_152), .Y (n_170));
  DFFRX1 \u_memory_dec_s2_reg[1] (.RN (rst_n), .CK (clk), .D (n_134),
       .Q (dec_s2[1]), .QN (UNCONNECTED14));
  DFFRX1 \u_memory_dec_s4_reg[1] (.RN (rst_n), .CK (clk), .D (n_133),
       .Q (dec_s4[1]), .QN (UNCONNECTED15));
  DFFRX1 \u_memory_dec_s6_reg[1] (.RN (rst_n), .CK (clk), .D (n_136),
       .Q (dec_s6[1]), .QN (UNCONNECTED16));
  DFFRX1 \u_memory_dec_s2_reg[3] (.RN (rst_n), .CK (clk), .D (n_132),
       .Q (dec_s2[3]), .QN (UNCONNECTED17));
  DFFRX1 \u_memory_dec_s4_reg[3] (.RN (rst_n), .CK (clk), .D (n_130),
       .Q (dec_s4[3]), .QN (UNCONNECTED18));
  NAND2X1 g6564__5107(.A (n_152), .B (n_150), .Y (n_164));
  OR2X1 g6561__6260(.A (n_152), .B (n_149), .Y (n_167));
  NAND2X1 g6560__4319(.A (n_152), .B (n_149), .Y (n_166));
  OR2X1 g6565__8428(.A (n_152), .B (n_150), .Y (n_163));
  CLKINVX1 g6566(.A (n_148), .Y (n_159));
  MX2X1 g6578__5526(.A (dec_s6[0]), .B (n_144), .S0 (n_146), .Y
       (n_147));
  CLKINVX1 g6577(.A (n_165), .Y (n_145));
  AOI22X1 g6576__6783(.A0 (n_116), .A1 (n_144), .B0 (n_127), .B1
       (n_137), .Y (n_148));
  OAI22X1 g6586__3680(.A0 (n_108), .A1 (n_143), .B0 (n_65), .B1
       (n_142), .Y (n_151));
  OAI22X1 g6585__1617(.A0 (n_76), .A1 (n_143), .B0 (n_74), .B1 (n_142),
       .Y (n_172));
  MX2X1 g6573__2802(.A (n_144), .B (dec_s4[0]), .S0 (n_215), .Y
       (n_141));
  MX2X1 g6569__1705(.A (dec_s2[2]), .B (n_143), .S0 (n_217), .Y
       (n_140));
  MX2X1 g6567__5122(.A (n_143), .B (dec_s4[2]), .S0 (n_215), .Y
       (n_139));
  MX2X1 g6574__8246(.A (dec_s2[0]), .B (n_144), .S0 (n_217), .Y
       (n_138));
  DFFRX1 \u_memory_o_data_reg[7] (.RN (rst_n), .CK (clk), .D (n_128),
       .Q (o_data[7]), .QN (UNCONNECTED19));
  OAI22X1 g6575__7098(.A0 (n_67), .A1 (n_137), .B0 (n_117), .B1
       (n_144), .Y (n_153));
  MX2X1 g6579__6131(.A (dec_s6[1]), .B (n_135), .S0 (n_146), .Y
       (n_136));
  AOI22X1 g6582__1881(.A0 (n_95), .A1 (n_131), .B0 (n_120), .B1
       (n_129), .Y (n_165));
  AOI22X1 g6583__5115(.A0 (n_86), .A1 (n_135), .B0 (n_121), .B1
       (n_126), .Y (n_168));
  MX2X1 g6584__7482(.A (n_261), .B (n_70), .S0 (n_135), .Y (n_149));
  MX2X1 g6570__4733(.A (dec_s2[1]), .B (n_135), .S0 (n_217), .Y
       (n_134));
  MX2X1 g6568__6161(.A (n_135), .B (dec_s4[1]), .S0 (n_215), .Y
       (n_133));
  MX2X1 g6572__9315(.A (dec_s2[3]), .B (n_131), .S0 (n_217), .Y
       (n_132));
  MX2X1 g6571__9945(.A (n_131), .B (dec_s4[3]), .S0 (n_215), .Y
       (n_130));
  OAI22X1 g6587__2883(.A0 (n_72), .A1 (n_129), .B0 (n_96), .B1 (n_131),
       .Y (n_150));
  MX2X1 g6542__2346(.A (n_123), .B (o_data[7]), .S0 (n_124), .Y
       (n_128));
  CLKINVX2 g6589(.A (n_142), .Y (n_143));
  DFFRX1 \u_memory_o_data_reg[6] (.RN (rst_n), .CK (clk), .D (n_125),
       .Q (o_data[6]), .QN (UNCONNECTED20));
  INVX2 g6595(.A (n_137), .Y (n_144));
  DFFRX1 \u_memory_rx_reg_reg[9] (.RN (rst_n), .CK (clk), .D (n_103),
       .Q (\u_memory_rx_reg[9]_306 ), .QN (UNCONNECTED21));
  DFFRX1 \u_memory_rx_reg_reg[5] (.RN (rst_n), .CK (clk), .D (n_106),
       .Q (\u_memory_rx_reg[5]_302 ), .QN (UNCONNECTED22));
  DFFRX1 \u_memory_rx_reg_reg[11] (.RN (rst_n), .CK (clk), .D (n_112),
       .Q (\u_memory_rx_reg[11]_308 ), .QN (UNCONNECTED23));
  DFFRX1 \u_memory_rx_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_100),
       .Q (\u_memory_rx_reg[2]_299 ), .QN (UNCONNECTED24));
  DFFRX1 \u_memory_rx_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_102),
       .Q (\u_memory_rx_reg[0]_297 ), .QN (UNCONNECTED25));
  NAND2X1 g6592__1666(.A (n_75), .B (n_109), .Y (n_142));
  NAND2X1 g6598__7410(.A (n_127), .B (n_118), .Y (n_137));
  DFFRX1 \u_memory_rx_reg_reg[14] (.RN (rst_n), .CK (clk), .D (n_110),
       .Q (rx_reg[14]), .QN (n_8));
  CLKINVX2 g6590(.A (n_129), .Y (n_131));
  CLKINVX2 g6591(.A (n_126), .Y (n_135));
  DFFRX1 \u_memory_rx_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_101),
       .Q (\u_memory_rx_reg[1]_298 ), .QN (UNCONNECTED26));
  DFFRX1 \u_memory_rx_reg_reg[10] (.RN (rst_n), .CK (clk), .D (n_114),
       .Q (\u_memory_rx_reg[10]_307 ), .QN (UNCONNECTED27));
  DFFRX1 \u_memory_rx_reg_reg[6] (.RN (rst_n), .CK (clk), .D (n_113),
       .Q (\u_memory_rx_reg[6]_303 ), .QN (UNCONNECTED28));
  DFFRX1 \u_memory_rx_reg_reg[4] (.RN (rst_n), .CK (clk), .D (n_115),
       .Q (\u_memory_rx_reg[4]_301 ), .QN (UNCONNECTED29));
  DFFRX1 \u_memory_rx_reg_reg[7] (.RN (rst_n), .CK (clk), .D (n_105),
       .Q (\u_memory_rx_reg[7]_304 ), .QN (UNCONNECTED30));
  DFFRX1 \u_memory_rx_reg_reg[8] (.RN (rst_n), .CK (clk), .D (n_104),
       .Q (\u_memory_rx_reg[8]_305 ), .QN (UNCONNECTED31));
  DFFRX1 \u_memory_rx_reg_reg[3] (.RN (rst_n), .CK (clk), .D (n_99), .Q
       (\u_memory_rx_reg[3]_300 ), .QN (UNCONNECTED32));
  DFFRX1 \u_memory_rx_reg_reg[15] (.RN (rst_n), .CK (clk), .D (n_107),
       .Q (rx_reg[15]), .QN (n_5));
  DFFRX1 \u_memory_rx_reg_reg[13] (.RN (rst_n), .CK (clk), .D (n_111),
       .Q (rx_reg[13]), .QN (n_6));
  DFFRX1 \u_memory_rx_reg_reg[12] (.RN (rst_n), .CK (clk), .D (n_119),
       .Q (rx_reg[12]), .QN (n_7));
  MX2X1 g6580__6417(.A (n_122), .B (o_data[6]), .S0 (n_124), .Y
       (n_125));
  MX4X1 g6581__5477(.A (dec_s2[0]), .B (dec_s2[2]), .C (dec_s2[1]), .D
       (dec_s2[3]), .S0 (n_77), .S1 (n_122), .Y (n_123));
  NAND2X1 g6594__2398(.A (n_121), .B (n_88), .Y (n_126));
  NAND2X1 g6593__5107(.A (n_120), .B (n_97), .Y (n_129));
  OAI21X1 g6629__6260(.A0 (n_7), .A1 (n_236), .B0 (n_61), .Y (n_119));
  OAI21X1 g6612__4319(.A0 (n_68), .A1 (n_117), .B0 (n_116), .Y (n_118));
  CLKINVX1 g6620(.A (n_94), .Y (n_115));
  CLKINVX1 g6621(.A (n_91), .Y (n_114));
  CLKINVX1 g6622(.A (n_90), .Y (n_113));
  CLKINVX1 g6623(.A (n_89), .Y (n_112));
  OAI21X1 g6625__8428(.A0 (n_6), .A1 (n_236), .B0 (n_64), .Y (n_111));
  OAI21X1 g6626__5526(.A0 (n_8), .A1 (n_236), .B0 (n_63), .Y (n_110));
  OAI21X1 g6611__6783(.A0 (n_66), .A1 (n_108), .B0 (n_73), .Y (n_109));
  OAI21X1 g6630__3680(.A0 (n_5), .A1 (n_236), .B0 (n_62), .Y (n_107));
  CLKINVX1 g6633(.A (n_98), .Y (n_106));
  CLKINVX1 g6634(.A (n_79), .Y (n_105));
  CLKINVX1 g6635(.A (n_84), .Y (n_104));
  CLKINVX1 g6636(.A (n_83), .Y (n_103));
  INVX1 g6637(.A (n_82), .Y (n_102));
  INVX1 g6638(.A (n_81), .Y (n_101));
  INVX1 g6639(.A (n_80), .Y (n_100));
  INVX1 g6640(.A (n_85), .Y (n_99));
  DFFRX1 \u_memory_o_data_reg[5] (.RN (rst_n), .CK (clk), .D (n_78), .Q
       (o_data[5]), .QN (UNCONNECTED33));
  AOI222X1 g6641__1617(.A0 (\u_memory_rx_reg[1]_298 ), .A1 (n_234), .B0
       (i_data[5]), .B1 (n_93), .C0 (\u_memory_rx_reg[5]_302 ), .C1
       (n_92), .Y (n_98));
  OAI21X1 g6610__2802(.A0 (n_71), .A1 (n_96), .B0 (n_95), .Y (n_97));
  AOI222X1 g6624__1705(.A0 (\u_memory_rx_reg[0]_297 ), .A1 (n_234), .B0
       (i_data[4]), .B1 (n_93), .C0 (\u_memory_rx_reg[4]_301 ), .C1
       (n_92), .Y (n_94));
  AOI222X1 g6627__5122(.A0 (\u_memory_rx_reg[6]_303 ), .A1 (n_234), .B0
       (i_data[10]), .B1 (n_93), .C0 (\u_memory_rx_reg[10]_307 ), .C1
       (n_92), .Y (n_91));
  AOI222X1 g6628__8246(.A0 (\u_memory_rx_reg[2]_299 ), .A1 (n_234), .B0
       (i_data[6]), .B1 (n_93), .C0 (\u_memory_rx_reg[6]_303 ), .C1
       (n_92), .Y (n_90));
  AOI222X1 g6631__7098(.A0 (\u_memory_rx_reg[7]_304 ), .A1 (n_234), .B0
       (i_data[11]), .B1 (n_93), .C0 (\u_memory_rx_reg[11]_308 ), .C1
       (n_92), .Y (n_89));
  OAI21X1 g6609__6131(.A0 (n_69), .A1 (n_261), .B0 (n_86), .Y (n_88));
  AOI22X1 g6648__1881(.A0 (\u_memory_rx_reg[3]_300 ), .A1 (n_92), .B0
       (i_data[3]), .B1 (n_93), .Y (n_85));
  AOI222X1 g6643__5115(.A0 (\u_memory_rx_reg[4]_301 ), .A1 (n_234), .B0
       (i_data[8]), .B1 (n_93), .C0 (\u_memory_rx_reg[8]_305 ), .C1
       (n_92), .Y (n_84));
  AOI222X1 g6644__7482(.A0 (\u_memory_rx_reg[5]_302 ), .A1 (n_234), .B0
       (i_data[9]), .B1 (n_93), .C0 (\u_memory_rx_reg[9]_306 ), .C1
       (n_92), .Y (n_83));
  AOI22X1 g6645__4733(.A0 (\u_memory_rx_reg[0]_297 ), .A1 (n_92), .B0
       (i_data[0]), .B1 (n_93), .Y (n_82));
  AOI22X1 g6646__6161(.A0 (\u_memory_rx_reg[1]_298 ), .A1 (n_92), .B0
       (i_data[1]), .B1 (n_93), .Y (n_81));
  AOI22X1 g6647__9315(.A0 (\u_memory_rx_reg[2]_299 ), .A1 (n_92), .B0
       (i_data[2]), .B1 (n_93), .Y (n_80));
  AOI222X1 g6642__9945(.A0 (\u_memory_rx_reg[3]_300 ), .A1 (n_234), .B0
       (i_data[7]), .B1 (n_93), .C0 (\u_memory_rx_reg[7]_304 ), .C1
       (n_92), .Y (n_79));
  MX2X1 g6596__2883(.A (n_77), .B (o_data[5]), .S0 (n_124), .Y (n_78));
  MX4X1 g6597__2346(.A (dec_s3[0]), .B (dec_s3[2]), .C (dec_s3[1]), .D
       (dec_s3[3]), .S0 (n_46), .S1 (n_77), .Y (n_122));
  CLKINVX1 g6651(.A (n_75), .Y (n_76));
  CLKINVX1 g6652(.A (n_73), .Y (n_74));
  DFFRX1 \u_memory_o_data_reg[4] (.RN (rst_n), .CK (clk), .D (n_47), .Q
       (o_data[4]), .QN (UNCONNECTED34));
  DFFRX1 \u_control_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_44), .Q
       (state[0]), .QN (UNCONNECTED35));
  CLKINVX1 g6666(.A (n_71), .Y (n_72));
  CLKINVX1 g6665(.A (n_69), .Y (n_70));
  CLKINVX1 g6653(.A (n_67), .Y (n_68));
  CLKINVX1 g6667(.A (n_65), .Y (n_66));
  INVX2 g6680(.A (n_92), .Y (n_236));
  AOI22X1 g6671__1666(.A0 (\u_memory_rx_reg[9]_306 ), .A1 (n_234), .B0
       (i_data[13]), .B1 (n_93), .Y (n_64));
  AOI22X1 g6669__7410(.A0 (\u_memory_rx_reg[10]_307 ), .A1 (n_234), .B0
       (i_data[14]), .B1 (n_93), .Y (n_63));
  AOI22X1 g6668__6417(.A0 (\u_memory_rx_reg[11]_308 ), .A1 (n_234), .B0
       (i_data[15]), .B1 (n_93), .Y (n_62));
  AOI22X1 g6672__5477(.A0 (\u_memory_rx_reg[8]_305 ), .A1 (n_234), .B0
       (i_data[12]), .B1 (n_93), .Y (n_61));
  NAND2X1 g6662__2398(.A (n_60), .B (n_57), .Y (n_127));
  DFFRX1 \u_memory_o_data_reg[3] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (o_data[3]), .QN (UNCONNECTED36));
  AOI211X1 g6664__5107(.A0 (pm01[1]), .A1 (n_53), .B0 (n_48), .C0
       (n_30), .Y (n_67));
  NAND2X1 g6663__6260(.A (n_60), .B (n_59), .Y (n_73));
  DFFRX1 \u_control_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_36), .Q
       (state[2]), .QN (n_9));
  NAND2X1 g6656__4319(.A (n_58), .B (n_59), .Y (n_116));
  NAND2X1 g6657__8428(.A (n_58), .B (n_57), .Y (n_75));
  NAND2X1 g6681__5526(.A (pm11[0]), .B (n_238), .Y (n_56));
  NAND2X1 g6682__6783(.A (pm10[0]), .B (n_238), .Y (n_55));
  NAND2X1 g6683__3680(.A (pm01[0]), .B (n_238), .Y (n_54));
  AOI211X1 g6676__1617(.A0 (pm00[1]), .A1 (n_53), .B0 (n_37), .C0
       (n_39), .Y (n_108));
  OAI211X1 g6673__1705(.A0 (n_52), .A1 (n_43), .B0 (n_50), .C0 (n_49),
       .Y (n_69));
  AND2X1 g6679__5122(.A (n_40), .B (n_38), .Y (n_117));
  AOI221X1 g6678__8246(.A0 (pm10[0]), .A1 (n_31), .B0 (pm10[1]), .B1
       (n_11), .C0 (n_51), .Y (n_96));
  OAI211X1 g6674__7098(.A0 (n_52), .A1 (n_45), .B0 (n_50), .C0 (n_49),
       .Y (n_71));
  NOR2X1 g6675__6131(.A (n_48), .B (n_33), .Y (n_65));
  AND2X2 g6687__1881(.A (n_233), .B (n_238), .Y (n_92));
  MX2X1 g6649__5115(.A (n_46), .B (o_data[4]), .S0 (n_124), .Y (n_47));
  NAND2X1 g6654__7482(.A (n_45), .B (n_41), .Y (n_95));
  DFFRX1 \u_memory_o_data_reg[2] (.RN (rst_n), .CK (clk), .D (n_26), .Q
       (o_data[2]), .QN (UNCONNECTED37));
  MX4X1 g6650__4733(.A (dec_s4[2]), .B (dec_s4[0]), .C (dec_s4[3]), .D
       (dec_s4[1]), .S0 (n_34), .S1 (n_46), .Y (n_77));
  OR3X1 g6670__6161(.A (n_146), .B (n_93), .C (n_217), .Y (n_44));
  NAND2X1 g6660__9315(.A (n_45), .B (n_42), .Y (n_121));
  NAND2X1 g6658__9945(.A (n_43), .B (n_42), .Y (n_120));
  NAND2X1 g6661__2883(.A (n_43), .B (n_41), .Y (n_86));
  CLKINVX1 g6696(.A (n_39), .Y (n_40));
  AOI21X1 g6691__2346(.A0 (pm00[1]), .A1 (n_3), .B0 (n_37), .Y (n_38));
  NAND2X1 g6707__1666(.A (n_21), .B (n_215), .Y (n_36));
  CLKINVX2 g6698(.A (n_234), .Y (n_238));
  OAI21X1 g6690__7410(.A0 (n_34), .A1 (n_124), .B0 (n_20), .Y (n_35));
  OAI21X1 g6688__6417(.A0 (n_32), .A1 (n_60), .B0 (n_29), .Y (n_33));
  AOI21X1 g6684__5477(.A0 (pm01[0]), .A1 (n_31), .B0 (pm01[1]), .Y
       (n_59));
  AOI21X1 g6692__2398(.A0 (pm00[0]), .A1 (n_31), .B0 (pm00[1]), .Y
       (n_57));
  DFFRX1 \u_control_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_23), .Q
       (state[1]), .QN (UNCONNECTED38));
  CLKINVX1 g6697(.A (n_29), .Y (n_30));
  NOR2X1 g6702__5107(.A (n_28), .B (n_31), .Y (n_39));
  NAND2X1 g6701__6260(.A (pm11[0]), .B (n_31), .Y (n_50));
  AOI21X1 g6693__4319(.A0 (pm10[0]), .A1 (n_27), .B0 (pm10[1]), .Y
       (n_42));
  AOI21X1 g6694__8428(.A0 (pm11[0]), .A1 (n_27), .B0 (pm11[1]), .Y
       (n_41));
  DFFRX1 u_memory_o_done_reg(.RN (rst_n), .CK (clk), .D (n_18), .Q
       (o_done), .QN (UNCONNECTED39));
  MX2X1 g6689__5526(.A (dec_s7), .B (o_data[2]), .S0 (n_124), .Y
       (n_26));
  AOI21X1 g6713__3680(.A0 (pm10[0]), .A1 (n_24), .B0 (n_31), .Y (n_51));
  OR2X2 g6705__1617(.A (n_17), .B (n_146), .Y (n_234));
  AOI21X1 g6708__2802(.A0 (state[0]), .A1 (state[1]), .B0 (n_22), .Y
       (n_23));
  NAND2X1 g6703__1705(.A (pm01[0]), .B (n_27), .Y (n_29));
  MX4X1 g6695__5122(.A (dec_s5[1]), .B (dec_s5[3]), .C (dec_s5[0]), .D
       (dec_s5[2]), .S0 (dec_s7), .S1 (n_34), .Y (n_46));
  NOR2X1 g6704__8246(.A (state[0]), .B (n_22), .Y (n_217));
  CLKINVX1 g6716(.A (n_146), .Y (n_21));
  NAND2X1 g6709__7098(.A (o_data[3]), .B (n_124), .Y (n_20));
  OAI21X1 g6710__6131(.A0 (pm11[1]), .A1 (n_0), .B0 (n_27), .Y (n_49));
  AOI21X1 g6712__1881(.A0 (pm00[0]), .A1 (n_19), .B0 (n_27), .Y (n_37));
  AOI21X1 g6711__5115(.A0 (pm01[0]), .A1 (n_32), .B0 (n_27), .Y (n_48));
  INVX2 g6721(.A (n_152), .Y (n_154));
  INVX2 g6722(.A (n_27), .Y (n_31));
  CLKINVX1 g6717(.A (n_124), .Y (n_18));
  NOR2X1 g6719__7482(.A (state[0]), .B (n_15), .Y (n_146));
  CLKINVX2 g6706(.A (n_93), .Y (n_233));
  CLKINVX1 g6715(.A (n_17), .Y (n_22));
  AND3X2 g6714__4733(.A (en), .B (n_9), .C (n_10), .Y (n_93));
  CLKAND2X2 g6725__6161(.A (n_45), .B (n_43), .Y (n_27));
  NAND2X1 g6724__9315(.A (n_173), .B (n_175), .Y (n_152));
  NAND2X1 g6720__9945(.A (state[0]), .B (n_14), .Y (n_124));
  CLKINVX1 g6728(.A (n_173), .Y (n_16));
  CLKINVX1 g6727(.A (n_14), .Y (n_15));
  CLKINVX1 g6731(.A (n_175), .Y (n_13));
  CLKINVX1 g6730(.A (n_45), .Y (n_12));
  CLKINVX1 g6729(.A (n_43), .Y (n_11));
  NOR2X1 g6718__2883(.A (state[2]), .B (n_10), .Y (n_17));
  AOI22X1 g6723__2346(.A0 (dec_s6[0]), .A1 (n_1), .B0 (dec_s6[1]), .B1
       (dec_s7), .Y (n_34));
  NAND3X1 g6726__1666(.A (state[0]), .B (n_9), .C (state[1]), .Y
       (n_215));
  NAND2X1 g6734__7410(.A (rx_reg[15]), .B (n_8), .Y (n_43));
  NAND2X1 g6733__6417(.A (rx_reg[13]), .B (n_7), .Y (n_173));
  NAND2X1 g6736__5477(.A (rx_reg[12]), .B (n_6), .Y (n_175));
  NAND2X1 g6735__2398(.A (rx_reg[14]), .B (n_5), .Y (n_45));
  CLKINVX1 g6738(.A (n_177), .Y (n_4));
  INVX2 g6739(.A (n_60), .Y (n_3));
  CLKINVX1 g6740(.A (n_169), .Y (n_2));
  NOR2X1 g6732__5107(.A (n_9), .B (state[1]), .Y (n_14));
  CLKINVX1 g6737(.A (n_53), .Y (n_58));
  NOR2X1 g6742__6260(.A (rx_reg[14]), .B (rx_reg[15]), .Y (n_53));
  NOR2X1 g6745__4319(.A (rx_reg[12]), .B (rx_reg[13]), .Y (n_169));
  NOR2X1 g6741__8428(.A (state[0]), .B (state[1]), .Y (n_10));
  NAND2X1 g6743__5526(.A (rx_reg[12]), .B (rx_reg[13]), .Y (n_177));
  NAND2X1 g6744__6783(.A (rx_reg[14]), .B (rx_reg[15]), .Y (n_60));
  AOI221X1 g2(.A0 (pm10[1]), .A1 (n_12), .B0 (n_31), .B1 (pm10[0]), .C0
       (n_51), .Y (n_261));
endmodule

