
// Generated by Cadence Genus(TM) Synthesis Solution 23.17-s085_1
// Generated on: May 17 2026 10:34:13 +07 (May 17 2026 03:34:13 UTC)

// Verification Directory fv/viterbi_decoder 

module viterbi_decoder(clk, rst_n, en, i_data, o_data, o_done);
  input clk, rst_n, en;
  input [15:0] i_data;
  output [7:0] o_data;
  output o_done;
  wire clk, rst_n, en;
  wire [15:0] i_data;
  wire [7:0] o_data;
  wire o_done;
  wire [1:0] pm10;
  wire [1:0] pm00;
  wire [1:0] pm01;
  wire [1:0] pm11;
  wire [3:0] dec_s3;
  wire [3:0] dec_s5;
  wire [1:0] dec_s6;
  wire [3:0] dec_s2;
  wire [3:0] dec_s4;
  wire [2:0] state;
  wire [15:0] rx_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, dec_s7, n_0, n_2,
       n_3, n_4;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_20, n_21, n_22;
  wire n_25, n_27, n_28, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_282, n_283;
  wire n_284, n_285;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  DFFSX1 \u_memory_pm10_reg[0] (.SN (rst_n), .CK (clk), .D (n_261), .Q
       (pm10[0]), .QN (UNCONNECTED));
  DFFSX1 \u_memory_pm10_reg[1] (.SN (rst_n), .CK (clk), .D (n_260), .Q
       (pm10[1]), .QN (n_2));
  DFFRX1 \u_memory_pm00_reg[0] (.RN (rst_n), .CK (clk), .D (n_258), .Q
       (pm00[0]), .QN (UNCONNECTED0));
  OAI21X1 g6868__2398(.A0 (n_259), .A1 (n_254), .B0 (n_68), .Y (n_261));
  OAI21X1 g6871__5107(.A0 (n_259), .A1 (n_248), .B0 (n_70), .Y (n_260));
  DFFRX1 \u_memory_pm00_reg[1] (.RN (rst_n), .CK (clk), .D (n_257), .Q
       (pm00[1]), .QN (n_0));
  DFFSX1 \u_memory_pm01_reg[0] (.SN (rst_n), .CK (clk), .D (n_255), .Q
       (pm01[0]), .QN (UNCONNECTED1));
  DFFSX1 \u_memory_pm11_reg[0] (.SN (rst_n), .CK (clk), .D (n_253), .Q
       (pm11[0]), .QN (UNCONNECTED2));
  DFFSX1 \u_memory_pm01_reg[1] (.SN (rst_n), .CK (clk), .D (n_245), .Q
       (pm01[1]), .QN (n_91));
  NOR2X1 g6881__6260(.A (n_256), .B (n_252), .Y (n_258));
  DFFRX1 \u_memory_dec_s3_reg[2] (.RN (rst_n), .CK (clk), .D (n_249),
       .Q (dec_s3[2]), .QN (UNCONNECTED3));
  DFFRX1 \u_memory_dec_s5_reg[2] (.RN (rst_n), .CK (clk), .D (n_251),
       .Q (dec_s5[2]), .QN (UNCONNECTED4));
  DFFSX1 \u_memory_pm11_reg[1] (.SN (rst_n), .CK (clk), .D (n_246), .Q
       (pm11[1]), .QN (n_6));
  DFFRX1 \u_memory_dec_s3_reg[0] (.RN (rst_n), .CK (clk), .D (n_241),
       .Q (dec_s3[0]), .QN (UNCONNECTED5));
  NOR2X1 g6880__4319(.A (n_256), .B (n_239), .Y (n_257));
  DFFRX1 \u_memory_dec_s5_reg[0] (.RN (rst_n), .CK (clk), .D (n_244),
       .Q (dec_s5[0]), .QN (UNCONNECTED6));
  OAI21X1 g6867__8428(.A0 (n_259), .A1 (n_224), .B0 (n_72), .Y (n_255));
  AOI22X1 g6889__5526(.A0 (n_284), .A1 (n_250), .B0 (n_207), .B1
       (n_247), .Y (n_254));
  OAI21X1 g6873__6783(.A0 (n_259), .A1 (n_230), .B0 (n_69), .Y (n_253));
  AOI21X1 g6890__3680(.A0 (n_215), .A1 (n_243), .B0 (n_236), .Y
       (n_252));
  MX2X1 g6892__1617(.A (n_250), .B (dec_s5[2]), .S0 (n_242), .Y
       (n_251));
  MX2X1 g6897__2802(.A (dec_s3[2]), .B (n_250), .S0 (n_240), .Y
       (n_249));
  AOI21X1 g6887__1705(.A0 (n_221), .A1 (n_247), .B0 (n_235), .Y
       (n_248));
  OAI21X1 g6874__5122(.A0 (n_259), .A1 (n_234), .B0 (n_73), .Y (n_246));
  OAI21X1 g6872__8246(.A0 (n_259), .A1 (n_228), .B0 (n_71), .Y (n_245));
  DFFRX1 u_memory_dec_s7_reg(.RN (rst_n), .CK (clk), .D (n_238), .Q
       (dec_s7), .QN (n_7));
  DFFRX1 \u_memory_dec_s3_reg[3] (.RN (rst_n), .CK (clk), .D (n_225),
       .Q (dec_s3[3]), .QN (UNCONNECTED7));
  DFFRX1 \u_memory_dec_s3_reg[1] (.RN (rst_n), .CK (clk), .D (n_226),
       .Q (dec_s3[1]), .QN (UNCONNECTED8));
  DFFRX1 \u_memory_dec_s5_reg[3] (.RN (rst_n), .CK (clk), .D (n_233),
       .Q (dec_s5[3]), .QN (UNCONNECTED9));
  MX2X1 g6886__7098(.A (n_243), .B (dec_s5[0]), .S0 (n_242), .Y
       (n_244));
  MX2X1 g6898__6131(.A (dec_s3[0]), .B (n_243), .S0 (n_240), .Y
       (n_241));
  AOI22X1 g6888__1881(.A0 (n_213), .A1 (n_243), .B0 (n_220), .B1
       (n_237), .Y (n_239));
  DFFRX1 \u_memory_dec_s5_reg[1] (.RN (rst_n), .CK (clk), .D (n_231),
       .Q (dec_s5[1]), .QN (UNCONNECTED10));
  OAI22X1 g6900__5115(.A0 (n_78), .A1 (n_237), .B0 (n_7), .B1 (n_165),
       .Y (n_238));
  AOI21X1 g6903__7482(.A0 (n_59), .A1 (n_214), .B0 (n_243), .Y (n_236));
  NOR2X1 g6904__4733(.A (n_222), .B (n_247), .Y (n_235));
  AOI22X1 g6894__6161(.A0 (n_204), .A1 (n_232), .B0 (n_217), .B1
       (n_229), .Y (n_234));
  MX2X1 g6893__9315(.A (n_232), .B (dec_s5[3]), .S0 (n_242), .Y
       (n_233));
  MX2X1 g6891__9945(.A (n_227), .B (dec_s5[1]), .S0 (n_242), .Y
       (n_231));
  AOI22X1 g6895__2883(.A0 (n_205), .A1 (n_232), .B0 (n_201), .B1
       (n_229), .Y (n_230));
  AOI22X1 g6901__2346(.A0 (n_209), .A1 (n_227), .B0 (n_212), .B1
       (n_223), .Y (n_228));
  MX2X1 g6899__1666(.A (dec_s3[1]), .B (n_227), .S0 (n_240), .Y
       (n_226));
  MX2X1 g6896__7410(.A (dec_s3[3]), .B (n_232), .S0 (n_240), .Y
       (n_225));
  AOI22X1 g6902__6417(.A0 (n_210), .A1 (n_227), .B0 (n_199), .B1
       (n_223), .Y (n_224));
  CLKINVX1 g6905(.A (n_247), .Y (n_250));
  CLKINVX2 g6906(.A (n_237), .Y (n_243));
  OAI21X1 g6907__5477(.A0 (n_222), .A1 (n_219), .B0 (n_221), .Y
       (n_247));
  NAND2X1 g6908__2398(.A (n_220), .B (n_216), .Y (n_237));
  CLKINVX2 g6909(.A (n_229), .Y (n_232));
  CLKINVX2 g6910(.A (n_223), .Y (n_227));
  NOR2X1 g6916__5107(.A (n_284), .B (n_208), .Y (n_219));
  NAND2X1 g6911__6260(.A (n_217), .B (n_206), .Y (n_229));
  OAI21X1 g6913__4319(.A0 (n_215), .A1 (n_214), .B0 (n_213), .Y
       (n_216));
  NAND2X1 g6912__8428(.A (n_212), .B (n_211), .Y (n_223));
  OAI21X1 g6915__5526(.A0 (n_210), .A1 (n_198), .B0 (n_209), .Y
       (n_211));
  CLKINVX1 g6925(.A (n_207), .Y (n_208));
  OAI21X1 g6914__6783(.A0 (n_205), .A1 (n_200), .B0 (n_204), .Y
       (n_206));
  OAI211X1 g6929__3680(.A0 (n_197), .A1 (n_169), .B0 (n_182), .C0
       (n_179), .Y (n_207));
  AOI211X1 g6933__1617(.A0 (n_203), .A1 (n_177), .B0 (n_178), .C0
       (n_183), .Y (n_214));
  NAND2X1 g6919__2802(.A (n_83), .B (n_202), .Y (n_220));
  NAND2X1 g6920__1705(.A (n_203), .B (n_185), .Y (n_213));
  NAND2X1 g6921__5122(.A (n_203), .B (n_202), .Y (n_221));
  CLKINVX1 g6926(.A (n_200), .Y (n_201));
  CLKINVX1 g6927(.A (n_198), .Y (n_199));
  NAND2X1 g6917__7098(.A (n_193), .B (n_196), .Y (n_217));
  NOR2X1 g6918__6131(.A (n_197), .B (n_184), .Y (n_222));
  NAND2X1 g6923__1881(.A (n_195), .B (n_196), .Y (n_212));
  AOI211X1 g6931__5115(.A0 (n_195), .A1 (n_192), .B0 (n_191), .C0
       (n_190), .Y (n_200));
  OAI211X1 g6932__7482(.A0 (n_197), .A1 (n_174), .B0 (n_194), .C0
       (n_180), .Y (n_215));
  AOI211X1 g6934__4733(.A0 (n_193), .A1 (n_192), .B0 (n_191), .C0
       (n_190), .Y (n_198));
  OAI211X1 g6930__6161(.A0 (n_84), .A1 (n_188), .B0 (n_187), .C0
       (n_186), .Y (n_210));
  NAND2X1 g6924__9315(.A (n_193), .B (n_189), .Y (n_209));
  NAND2X1 g6922__9945(.A (n_195), .B (n_189), .Y (n_204));
  OAI211X1 g6935__2883(.A0 (n_86), .A1 (n_188), .B0 (n_187), .C0
       (n_186), .Y (n_205));
  CLKINVX1 g6938(.A (n_184), .Y (n_185));
  CLKINVX1 g6952(.A (n_182), .Y (n_183));
  CLKINVX1 g6951(.A (n_178), .Y (n_179));
  AOI21X1 g6937__1666(.A0 (n_172), .A1 (n_176), .B0 (n_177), .Y
       (n_202));
  DFFRX1 \u_memory_dec_s6_reg[0] (.RN (rst_n), .CK (clk), .D (n_167),
       .Q (dec_s6[0]), .QN (UNCONNECTED11));
  DFFRX1 \u_memory_dec_s2_reg[0] (.RN (rst_n), .CK (clk), .D (n_168),
       .Q (dec_s2[0]), .QN (UNCONNECTED12));
  DFFRX1 \u_memory_dec_s4_reg[0] (.RN (rst_n), .CK (clk), .D (n_164),
       .Q (dec_s4[0]), .QN (UNCONNECTED13));
  NOR2X1 g6955__7410(.A (n_175), .B (n_176), .Y (n_178));
  AOI21X1 g6940__6417(.A0 (n_175), .A1 (n_171), .B0 (n_192), .Y
       (n_196));
  OAI21X1 g6939__5477(.A0 (n_175), .A1 (n_170), .B0 (n_174), .Y
       (n_184));
  NAND2X1 g6956__2398(.A (n_175), .B (n_176), .Y (n_182));
  NAND2X1 g6953__5107(.A (n_203), .B (n_158), .Y (n_173));
  DFFRX1 \u_memory_dec_s2_reg[2] (.RN (rst_n), .CK (clk), .D (n_161),
       .Q (dec_s2[2]), .QN (UNCONNECTED14));
  DFFRX1 \u_memory_dec_s4_reg[2] (.RN (rst_n), .CK (clk), .D (n_157),
       .Q (dec_s4[2]), .QN (UNCONNECTED15));
  AOI21X1 g6941__6260(.A0 (n_175), .A1 (n_163), .B0 (n_156), .Y
       (n_189));
  NOR2X1 g6960__4319(.A (n_172), .B (n_171), .Y (n_191));
  AND2X1 g6959__8428(.A (n_171), .B (n_172), .Y (n_190));
  NAND2X1 g6957__5526(.A (n_172), .B (n_170), .Y (n_180));
  CLKINVX1 g6963(.A (n_169), .Y (n_177));
  DFFRX1 \u_memory_dec_s4_reg[1] (.RN (rst_n), .CK (clk), .D (n_150),
       .Q (dec_s4[1]), .QN (UNCONNECTED16));
  DFFRX1 \u_memory_dec_s2_reg[3] (.RN (rst_n), .CK (clk), .D (n_149),
       .Q (dec_s2[3]), .QN (UNCONNECTED17));
  DFFRX1 \u_memory_dec_s2_reg[1] (.RN (rst_n), .CK (clk), .D (n_154),
       .Q (dec_s2[1]), .QN (UNCONNECTED18));
  DFFRX1 \u_memory_dec_s4_reg[3] (.RN (rst_n), .CK (clk), .D (n_148),
       .Q (dec_s4[3]), .QN (UNCONNECTED19));
  DFFRX1 \u_memory_dec_s6_reg[1] (.RN (rst_n), .CK (clk), .D (n_147),
       .Q (dec_s6[1]), .QN (UNCONNECTED20));
  NAND2X1 g6958__6783(.A (n_175), .B (n_155), .Y (n_194));
  MX2X1 g6978__3680(.A (dec_s2[0]), .B (n_166), .S0 (n_240), .Y
       (n_168));
  MX2X1 g6977__1617(.A (dec_s6[0]), .B (n_166), .S0 (n_165), .Y
       (n_167));
  MX2X1 g6969__2802(.A (n_166), .B (dec_s4[0]), .S0 (n_242), .Y
       (n_164));
  OR2X1 g6961__1705(.A (n_172), .B (n_163), .Y (n_186));
  NAND2X1 g6962__5122(.A (n_172), .B (n_163), .Y (n_187));
  AOI22X1 g6972__8246(.A0 (n_141), .A1 (n_166), .B0 (n_145), .B1
       (n_162), .Y (n_169));
  OAI22X1 g6971__7098(.A0 (n_130), .A1 (n_162), .B0 (n_142), .B1
       (n_166), .Y (n_176));
  MX2X1 g6966__6131(.A (dec_s2[2]), .B (n_160), .S0 (n_240), .Y
       (n_161));
  OAI22X1 g6983__1881(.A0 (n_138), .A1 (n_160), .B0 (n_129), .B1
       (n_159), .Y (n_171));
  OAI22X1 g6982__5115(.A0 (n_122), .A1 (n_160), .B0 (n_120), .B1
       (n_159), .Y (n_192));
  CLKINVX1 g6973(.A (n_174), .Y (n_158));
  MX2X1 g6970__7482(.A (n_160), .B (dec_s4[2]), .S0 (n_242), .Y
       (n_157));
  CLKINVX1 g6975(.A (n_188), .Y (n_156));
  CLKINVX2 g6974(.A (n_155), .Y (n_170));
  MX2X1 g6964__4733(.A (dec_s2[1]), .B (n_153), .S0 (n_240), .Y
       (n_154));
  OAI22X1 g6980__6161(.A0 (n_124), .A1 (n_146), .B0 (n_136), .B1
       (n_153), .Y (n_155));
  AOI22X1 g6984__9315(.A0 (n_132), .A1 (n_151), .B0 (n_144), .B1
       (n_152), .Y (n_188));
  OAI22X1 g6981__9945(.A0 (n_127), .A1 (n_152), .B0 (n_285), .B1
       (n_151), .Y (n_163));
  MX2X1 g6968__2883(.A (n_153), .B (dec_s4[1]), .S0 (n_242), .Y
       (n_150));
  MX2X1 g6967__2346(.A (dec_s2[3]), .B (n_151), .S0 (n_240), .Y
       (n_149));
  MX2X1 g6965__1666(.A (n_151), .B (dec_s4[3]), .S0 (n_242), .Y
       (n_148));
  MX2X1 g6976__7410(.A (dec_s6[1]), .B (n_153), .S0 (n_165), .Y
       (n_147));
  AOI22X1 g6979__6417(.A0 (n_135), .A1 (n_153), .B0 (n_140), .B1
       (n_146), .Y (n_174));
  CLKINVX2 g6989(.A (n_162), .Y (n_166));
  CLKINVX2 g6985(.A (n_159), .Y (n_160));
  NAND2X1 g6992__5477(.A (n_145), .B (n_143), .Y (n_162));
  NAND2X1 g6987__2398(.A (n_121), .B (n_139), .Y (n_159));
  CLKINVX2 g6988(.A (n_152), .Y (n_151));
  CLKINVX2 g6990(.A (n_146), .Y (n_153));
  NAND2X1 g6991__5107(.A (n_144), .B (n_134), .Y (n_152));
  OAI21X1 g6996__6260(.A0 (n_131), .A1 (n_142), .B0 (n_141), .Y
       (n_143));
  NAND2X1 g6993__4319(.A (n_140), .B (n_137), .Y (n_146));
  OAI21X1 g6994__8428(.A0 (n_128), .A1 (n_138), .B0 (n_119), .Y
       (n_139));
  OAI21X1 g6995__5526(.A0 (n_123), .A1 (n_136), .B0 (n_135), .Y
       (n_137));
  OAI21X1 g6997__6783(.A0 (n_126), .A1 (n_285), .B0 (n_132), .Y
       (n_134));
  CLKINVX1 g7000(.A (n_130), .Y (n_131));
  CLKINVX1 g7014(.A (n_128), .Y (n_129));
  CLKINVX1 g7012(.A (n_126), .Y (n_127));
  OAI211X1 g7020__3680(.A0 (n_91), .A1 (n_113), .B0 (n_98), .C0
       (n_125), .Y (n_128));
  CLKAND2X2 g7003__1617(.A (n_125), .B (n_111), .Y (n_130));
  CLKINVX1 g7013(.A (n_123), .Y (n_124));
  AOI211X1 g7021__2802(.A0 (pm00[1]), .A1 (n_110), .B0 (n_108), .C0
       (n_100), .Y (n_138));
  AND2X1 g7019__1705(.A (n_99), .B (n_109), .Y (n_142));
  CLKINVX1 g7002(.A (n_121), .Y (n_122));
  CLKINVX1 g7001(.A (n_119), .Y (n_120));
  NAND2X1 g7006__5122(.A (n_116), .B (n_117), .Y (n_144));
  NAND2X1 g7007__8246(.A (n_118), .B (n_114), .Y (n_132));
  NAND2X1 g7009__7098(.A (n_118), .B (n_117), .Y (n_140));
  OAI211X1 g7018__6131(.A0 (n_6), .A1 (n_116), .B0 (n_115), .C0 (n_93),
       .Y (n_123));
  NAND2X1 g7017__1881(.A (n_115), .B (n_103), .Y (n_126));
  NAND2X1 g7010__5115(.A (n_116), .B (n_114), .Y (n_135));
  DFFRX1 \u_memory_o_data_reg[7] (.RN (rst_n), .CK (clk), .D (n_104),
       .Q (o_data[7]), .QN (UNCONNECTED21));
  NAND2X1 g7004__4733(.A (n_107), .B (n_112), .Y (n_141));
  NAND2X1 g7005__6161(.A (n_113), .B (n_112), .Y (n_119));
  NAND2X1 g7008__9315(.A (n_113), .B (n_106), .Y (n_145));
  AOI21X1 g7024__9945(.A0 (pm01[1]), .A1 (n_110), .B0 (n_97), .Y
       (n_111));
  AOI21X1 g7029__2883(.A0 (pm00[1]), .A1 (n_82), .B0 (n_108), .Y
       (n_109));
  NAND2X1 g7011__2346(.A (n_107), .B (n_106), .Y (n_121));
  AOI221X1 g7023__1666(.A0 (n_94), .A1 (n_102), .B0 (n_101), .B1
       (pm10[1]), .C0 (n_105), .Y (n_136));
  MX2X1 g6998__7410(.A (n_90), .B (o_data[7]), .S0 (n_87), .Y (n_104));
  AOI22X1 g7028__6417(.A0 (n_92), .A1 (n_102), .B0 (pm11[1]), .B1
       (n_101), .Y (n_103));
  AOI21X1 g7030__5477(.A0 (pm10[0]), .A1 (n_102), .B0 (pm10[1]), .Y
       (n_117));
  CLKINVX1 g7032(.A (n_99), .Y (n_100));
  CLKINVX1 g7038(.A (n_97), .Y (n_98));
  AOI21X1 g7031__2398(.A0 (pm11[0]), .A1 (n_102), .B0 (pm11[1]), .Y
       (n_114));
  AOI21X1 g7027__5107(.A0 (pm01[0]), .A1 (n_96), .B0 (pm01[1]), .Y
       (n_112));
  AOI21X1 g7025__6260(.A0 (pm00[0]), .A1 (n_96), .B0 (pm00[1]), .Y
       (n_106));
  DFFRX1 \u_memory_o_data_reg[6] (.RN (rst_n), .CK (clk), .D (n_89), .Q
       (o_data[6]), .QN (UNCONNECTED22));
  NAND2X1 g7034__4319(.A (pm01[0]), .B (n_102), .Y (n_125));
  NAND2X1 g7041__5526(.A (n_92), .B (n_102), .Y (n_93));
  NAND2X1 g7035__6783(.A (pm00[0]), .B (n_102), .Y (n_99));
  AOI21X1 g7040__3680(.A0 (pm01[0]), .A1 (n_91), .B0 (n_102), .Y
       (n_97));
  AOI21X1 g7042__1617(.A0 (pm00[0]), .A1 (n_0), .B0 (n_102), .Y
       (n_108));
  AND2X1 g7033__2802(.A (n_96), .B (pm10[0]), .Y (n_105));
  NAND2X1 g7036__1705(.A (pm11[0]), .B (n_96), .Y (n_115));
  MX4X1 g7015__5122(.A (dec_s2[0]), .B (dec_s2[2]), .C (dec_s2[1]), .D
       (dec_s2[3]), .S0 (n_80), .S1 (n_88), .Y (n_90));
  MX2X1 g7016__8246(.A (n_88), .B (o_data[6]), .S0 (n_87), .Y (n_89));
  CLKINVX2 g7046(.A (n_172), .Y (n_175));
  CLKINVX2 g7045(.A (n_96), .Y (n_102));
  DFFRX1 \u_memory_o_data_reg[5] (.RN (rst_n), .CK (clk), .D (n_81), .Q
       (o_data[5]), .QN (UNCONNECTED23));
  NAND2X2 g7047__7098(.A (n_116), .B (n_118), .Y (n_96));
  NAND2X1 g7048__6131(.A (n_193), .B (n_195), .Y (n_172));
  CLKINVX1 g7068(.A (n_193), .Y (n_86));
  DFFRX1 \u_control_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_79), .Q
       (state[0]), .QN (n_17));
  CLKINVX1 g7069(.A (n_116), .Y (n_85));
  CLKINVX1 g7070(.A (n_195), .Y (n_84));
  CLKINVX1 g7071(.A (n_118), .Y (n_101));
  CLKINVX1 g7065(.A (n_197), .Y (n_83));
  CLKINVX1 g7066(.A (n_113), .Y (n_82));
  MX2X1 g7039__1881(.A (n_80), .B (o_data[5]), .S0 (n_87), .Y (n_81));
  MX4X1 g7043__5115(.A (dec_s3[0]), .B (dec_s3[2]), .C (dec_s3[1]), .D
       (dec_s3[3]), .S0 (n_62), .S1 (n_80), .Y (n_88));
  CLKINVX1 g7067(.A (n_110), .Y (n_107));
  NAND2X1 g7086__7482(.A (n_77), .B (n_67), .Y (n_118));
  NAND2X2 g7084__4733(.A (n_76), .B (n_64), .Y (n_116));
  NAND2X1 g7085__6161(.A (n_66), .B (n_74), .Y (n_195));
  NAND2X1 g7083__9315(.A (n_65), .B (n_75), .Y (n_193));
  NAND3X1 g7121__9945(.A (n_78), .B (n_21), .C (n_55), .Y (n_79));
  DFFRX1 \u_memory_o_data_reg[4] (.RN (rst_n), .CK (clk), .D (n_63), .Q
       (o_data[4]), .QN (UNCONNECTED24));
  DFFRX1 \u_control_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_60), .Q
       (state[1]), .QN (n_50));
  DFFRX1 \u_control_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_61), .Q
       (state[2]), .QN (n_8));
  DFFRX1 \u_memory_o_data_reg[3] (.RN (rst_n), .CK (clk), .D (n_58), .Q
       (o_data[3]), .QN (UNCONNECTED25));
  NOR2X1 g7082__2883(.A (n_77), .B (n_76), .Y (n_110));
  NOR2X1 g7079__2346(.A (n_75), .B (n_74), .Y (n_197));
  NAND2X1 g7081__1666(.A (n_77), .B (n_76), .Y (n_113));
  NAND2X1 g7080__7410(.A (n_75), .B (n_74), .Y (n_203));
  AOI21X1 g7074__6417(.A0 (pm11[1]), .A1 (n_259), .B0 (n_256), .Y
       (n_73));
  AOI21X1 g7072__5477(.A0 (pm01[0]), .A1 (n_259), .B0 (n_256), .Y
       (n_72));
  AOI21X1 g7076__2398(.A0 (pm01[1]), .A1 (n_259), .B0 (n_256), .Y
       (n_71));
  AOI21X1 g7075__5107(.A0 (pm10[1]), .A1 (n_259), .B0 (n_256), .Y
       (n_70));
  DFFRX1 \u_memory_o_data_reg[2] (.RN (rst_n), .CK (clk), .D (n_54), .Q
       (o_data[2]), .QN (UNCONNECTED26));
  AOI21X1 g7077__6260(.A0 (pm11[0]), .A1 (n_259), .B0 (n_256), .Y
       (n_69));
  AOI21X1 g7078__4319(.A0 (pm10[0]), .A1 (n_259), .B0 (n_256), .Y
       (n_68));
  CLKINVX2 g7088(.A (n_76), .Y (n_67));
  CLKINVX1 g7089(.A (n_75), .Y (n_66));
  CLKINVX1 g7090(.A (n_74), .Y (n_65));
  INVX2 g7091(.A (n_77), .Y (n_64));
  MX2X1 g7073__8428(.A (n_62), .B (o_data[4]), .S0 (n_87), .Y (n_63));
  NAND2X1 g7133__5526(.A (n_78), .B (n_242), .Y (n_61));
  OR2X1 g7132__6783(.A (n_56), .B (n_240), .Y (n_60));
  NAND2X1 g7094__3680(.A (pm00[0]), .B (n_259), .Y (n_59));
  MX4X1 g7087__1617(.A (dec_s4[2]), .B (dec_s4[0]), .C (dec_s4[3]), .D
       (dec_s4[1]), .S0 (n_57), .S1 (n_62), .Y (n_80));
  OAI21X1 g7120__2802(.A0 (n_87), .A1 (n_57), .B0 (n_52), .Y (n_58));
  AOI221X1 g7100__1705(.A0 (rx_reg[12]), .A1 (n_56), .B0 (rx_reg[0]),
       .B1 (n_165), .C0 (n_44), .Y (n_75));
  NAND2X1 g7099__5122(.A (n_27), .B (n_51), .Y (n_76));
  NAND2X2 g7102__8246(.A (n_283), .B (n_53), .Y (n_77));
  AOI221X1 g7101__7098(.A0 (rx_reg[13]), .A1 (n_56), .B0 (rx_reg[1]),
       .B1 (n_165), .C0 (n_45), .Y (n_74));
  DFFRX1 u_memory_o_done_reg(.RN (rst_n), .CK (clk), .D (n_48), .Q
       (o_done), .QN (UNCONNECTED27));
  CLKINVX1 g7139(.A (n_240), .Y (n_55));
  MX2X1 g7122__6131(.A (dec_s7), .B (o_data[2]), .S0 (n_87), .Y (n_54));
  DFFRX1 \u_memory_rx_reg_reg[11] (.RN (rst_n), .CK (clk), .D (n_34),
       .Q (rx_reg[11]), .QN (n_4));
  DFFRX1 \u_memory_rx_reg_reg[15] (.RN (rst_n), .CK (clk), .D (n_37),
       .Q (rx_reg[15]), .QN (UNCONNECTED28));
  DFFRX1 \u_memory_rx_reg_reg[12] (.RN (rst_n), .CK (clk), .D (n_36),
       .Q (rx_reg[12]), .QN (UNCONNECTED29));
  DFFRX1 \u_memory_rx_reg_reg[5] (.RN (rst_n), .CK (clk), .D (n_31), .Q
       (rx_reg[5]), .QN (UNCONNECTED30));
  DFFRX1 \u_memory_rx_reg_reg[13] (.RN (rst_n), .CK (clk), .D (n_32),
       .Q (rx_reg[13]), .QN (UNCONNECTED31));
  DFFRX1 \u_memory_rx_reg_reg[0] (.RN (rst_n), .CK (clk), .D (n_42), .Q
       (rx_reg[0]), .QN (UNCONNECTED32));
  DFFRX1 \u_memory_rx_reg_reg[8] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (rx_reg[8]), .QN (UNCONNECTED33));
  DFFRX1 \u_memory_rx_reg_reg[3] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (rx_reg[3]), .QN (UNCONNECTED34));
  DFFRX1 \u_memory_rx_reg_reg[7] (.RN (rst_n), .CK (clk), .D (n_40), .Q
       (rx_reg[7]), .QN (n_3));
  DFFRX1 \u_memory_rx_reg_reg[10] (.RN (rst_n), .CK (clk), .D (n_39),
       .Q (rx_reg[10]), .QN (UNCONNECTED35));
  DFFRX1 \u_memory_rx_reg_reg[6] (.RN (rst_n), .CK (clk), .D (n_47), .Q
       (rx_reg[6]), .QN (UNCONNECTED36));
  DFFRX1 \u_memory_rx_reg_reg[2] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (rx_reg[2]), .QN (UNCONNECTED37));
  DFFRX1 \u_memory_rx_reg_reg[14] (.RN (rst_n), .CK (clk), .D (n_30),
       .Q (rx_reg[14]), .QN (UNCONNECTED38));
  DFFRX1 \u_memory_rx_reg_reg[4] (.RN (rst_n), .CK (clk), .D (n_33), .Q
       (rx_reg[4]), .QN (UNCONNECTED39));
  DFFRX1 \u_memory_rx_reg_reg[9] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (rx_reg[9]), .QN (UNCONNECTED40));
  DFFRX1 \u_memory_rx_reg_reg[1] (.RN (rst_n), .CK (clk), .D (n_35), .Q
       (rx_reg[1]), .QN (UNCONNECTED41));
  NAND2X1 g7117__1881(.A (n_50), .B (n_25), .Y (n_53));
  NAND2X1 g7131__5115(.A (o_data[3]), .B (n_87), .Y (n_52));
  NAND2X1 g7145__7482(.A (state[0]), .B (n_22), .Y (n_242));
  NAND2X1 g7116__4733(.A (n_50), .B (n_28), .Y (n_51));
  AND2X2 g7146__6161(.A (n_17), .B (n_22), .Y (n_240));
  NOR3X1 g7124__9315(.A (n_22), .B (n_165), .C (n_56), .Y (n_259));
  CLKINVX1 g7138(.A (n_87), .Y (n_48));
  MX2X1 g7110__9945(.A (rx_reg[6]), .B (i_data[6]), .S0 (n_256), .Y
       (n_47));
  MX2X1 g7104__2883(.A (rx_reg[8]), .B (i_data[8]), .S0 (n_256), .Y
       (n_46));
  NOR2X1 g7126__2346(.A (n_20), .B (n_10), .Y (n_45));
  NOR2X1 g7128__1666(.A (n_20), .B (n_11), .Y (n_44));
  MX2X1 g7092__7410(.A (rx_reg[3]), .B (i_data[3]), .S0 (n_256), .Y
       (n_43));
  MX2X1 g7093__6417(.A (rx_reg[0]), .B (i_data[0]), .S0 (n_256), .Y
       (n_42));
  MX2X1 g7095__5477(.A (rx_reg[9]), .B (i_data[9]), .S0 (n_256), .Y
       (n_41));
  MX2X1 g7096__2398(.A (rx_reg[7]), .B (i_data[7]), .S0 (n_256), .Y
       (n_40));
  MX4X1 g7123__5107(.A (dec_s5[1]), .B (dec_s5[3]), .C (dec_s5[0]), .D
       (dec_s5[2]), .S0 (dec_s7), .S1 (n_57), .Y (n_62));
  MX2X1 g7105__6260(.A (rx_reg[10]), .B (i_data[10]), .S0 (n_256), .Y
       (n_39));
  MX2X1 g7106__4319(.A (rx_reg[2]), .B (i_data[2]), .S0 (n_256), .Y
       (n_38));
  MX2X1 g7107__8428(.A (rx_reg[15]), .B (i_data[15]), .S0 (n_256), .Y
       (n_37));
  MX2X1 g7108__5526(.A (rx_reg[12]), .B (i_data[12]), .S0 (n_256), .Y
       (n_36));
  MX2X1 g7109__6783(.A (rx_reg[1]), .B (i_data[1]), .S0 (n_256), .Y
       (n_35));
  MX2X1 g7111__3680(.A (rx_reg[11]), .B (i_data[11]), .S0 (n_256), .Y
       (n_34));
  MX2X1 g7112__1617(.A (rx_reg[4]), .B (i_data[4]), .S0 (n_256), .Y
       (n_33));
  MX2X1 g7113__2802(.A (rx_reg[13]), .B (i_data[13]), .S0 (n_256), .Y
       (n_32));
  MX2X1 g7114__1705(.A (rx_reg[5]), .B (i_data[5]), .S0 (n_256), .Y
       (n_31));
  MX2X1 g7115__5122(.A (rx_reg[14]), .B (i_data[14]), .S0 (n_256), .Y
       (n_30));
  NAND2X1 g7135__7098(.A (n_18), .B (n_9), .Y (n_28));
  CLKINVX2 g7137(.A (n_165), .Y (n_78));
  NAND2X1 g7129__6131(.A (n_22), .B (n_15), .Y (n_27));
  NAND2X1 g7134__1881(.A (n_14), .B (n_16), .Y (n_25));
  NAND2X1 g7144__5115(.A (state[0]), .B (n_13), .Y (n_87));
  CLKINVX1 g7160(.A (n_22), .Y (n_20));
  CLKINVX1 g7130(.A (n_256), .Y (n_21));
  NOR2X1 g7143__7482(.A (state[0]), .B (n_12), .Y (n_165));
  NAND3X1 g7152__6161(.A (rx_reg[3]), .B (state[2]), .C (n_17), .Y
       (n_18));
  NAND3X1 g7141__9315(.A (rx_reg[14]), .B (state[0]), .C (n_8), .Y
       (n_16));
  OAI22X1 g7150__9945(.A0 (n_4), .A1 (state[0]), .B0 (n_3), .B1 (n_17),
       .Y (n_15));
  NOR3X1 g7142__2883(.A (state[1]), .B (n_17), .C (state[2]), .Y
       (n_56));
  NAND3X1 g7147__2346(.A (rx_reg[2]), .B (state[2]), .C (n_17), .Y
       (n_14));
  CLKINVX1 g7156(.A (n_12), .Y (n_13));
  AOI22X1 g7151__1666(.A0 (n_17), .A1 (rx_reg[8]), .B0 (state[0]), .B1
       (rx_reg[4]), .Y (n_11));
  AOI22X1 g7149__7410(.A0 (n_17), .A1 (rx_reg[9]), .B0 (state[0]), .B1
       (rx_reg[5]), .Y (n_10));
  NAND3X1 g7140__6417(.A (rx_reg[15]), .B (state[0]), .C (n_8), .Y
       (n_9));
  AOI22X1 g7153__5477(.A0 (dec_s6[0]), .A1 (n_7), .B0 (dec_s6[1]), .B1
       (dec_s7), .Y (n_57));
  AND4X2 g7136__2398(.A (n_50), .B (n_8), .C (n_17), .D (en), .Y
       (n_256));
  NAND2X1 g7155__5107(.A (pm11[0]), .B (n_6), .Y (n_92));
  NAND2X1 g7154__6260(.A (pm10[0]), .B (n_2), .Y (n_94));
  NAND2X1 g7163__4319(.A (state[2]), .B (n_50), .Y (n_12));
  CLKAND2X2 g7164__8428(.A (state[1]), .B (n_8), .Y (n_22));
  NAND2X1 g2(.A (n_282), .B (n_22), .Y (n_283));
  MX2X1 g3(.A (rx_reg[10]), .B (rx_reg[6]), .S0 (state[0]), .Y (n_282));
  NAND3X1 g7229(.A (n_194), .B (n_180), .C (n_173), .Y (n_284));
  AOI221X1 g7230(.A0 (n_102), .A1 (n_94), .B0 (pm10[1]), .B1 (n_85),
       .C0 (n_105), .Y (n_285));
endmodule

